import {
    extractAlpineDirectives,
    parseElements,
    type AlpineDirectiveNode,
    type ParsedElement,
} from "../directiveExtractor.js";
import type { OffsetRange } from "../types.js";
import {
    DATA_ALIAS_CAPS,
    DATA_DECLARATION_CAPS,
    HANDLER_BODY_CAPS,
    RENDER_EXPRESSION_CAPS,
    type MappingCapabilities,
} from "./mappingCapabilities.js";
import { parseDataLiteral, type DataMemberDescriptor, type DataMemberParameterDescriptor } from "./xDataAst.js";
import type {
    MappingEntry,
    VirtualCodeAdapter,
    VirtualCodeFile,
} from "./types.js";

const STAGE4_DIRECTIVES = new Set([
    "x-data",
    "x-text",
    "x-show",
    "x-on",
    "x-bind",
    "x-model",
    "x-modelable",
]);

const ALPINE_XDATA_HELPER = "__alpine_internal_xdata";
const ALPINE_MAGIC_SCOPE = "__alpine_internal_magic_scope";

type IdGen = () => string;

function createIdGen(): IdGen {
    let counter = 0;
    return () => {
        counter += 1;
        return `__alpine_internal_${counter.toString(36)}`;
    };
}

export interface GeneratorOptions {
    documentId?: string;
}

export interface ResolvedXDataSource {
    expressionText: string;
    expressionRange: OffsetRange;
    members: ReadonlyArray<DataMemberDescriptor>;
}

export interface VirtualBuildOptions {
    resolvedXDataByAttribute?: ReadonlyMap<string, ResolvedXDataSource>;
}

export function createAlpineVirtualCodeAdapter(
    options: GeneratorOptions = {},
): VirtualCodeAdapter {
    const documentId = options.documentId ?? "alpine-virtual-code";
    return {
        id: documentId,
        languageId: "typescript",
        generate: (input: string) => generateAlpineVirtualCode(input, documentId),
    };
}

export interface ExternDeclaration {
    name: string;
    kind: "property" | "method" | "init";
    type: "boolean" | "number" | "string" | "unknown" | "void";
}

export function generateAlpineVirtualCode(
    input: string,
    documentId: string,
    externs: ReadonlyArray<ExternDeclaration> = [],
    options: VirtualBuildOptions = {},
): VirtualCodeFile {
    const ids = createIdGen();
    const directives = extractAlpineDirectives(input);
    const roots = parseElements(input);
    const directiveByAttribute = new Map<string, AlpineDirectiveNode>();
    for (const directive of directives) {
        directiveByAttribute.set(attributeRangeKey(directive.attributeRange), directive);
    }
    const state: BuildState = {
        code: "",
        mappings: [],
        internalIdentifiers: new Set(),
    };

    state.code = [
        `// Generated by Alpine Language Tools — DO NOT EDIT.`,
        `// Source document: ${documentId}.`,
        `// Source length: ${input.length}.`,
        ``,
        `type ${ALPINE_MAGIC_SCOPE}<T extends object> = {`,
        `    $el: HTMLElement;`,
        `    $refs: Record<string, HTMLElement>;`,
        `    $store: Record<string, unknown>;`,
        `    $watch: (path: string, callback: (value: unknown, oldValue: unknown) => void) => void;`,
        `    $dispatch: (name: string, detail?: unknown, options?: CustomEventInit<unknown>) => boolean;`,
        `    $nextTick: (callback?: () => void) => Promise<void>;`,
        `    $root: HTMLElement;`,
        `    $data: T;`,
        `    $id: (name: string, ...keys: Array<string | number>) => string;`,
        `};`,
        `declare function ${ALPINE_XDATA_HELPER}<T extends object>(value: T & ThisType<T & ${ALPINE_MAGIC_SCOPE}<T>>): T;`,
        ``,
    ].join("\n");
    state.internalIdentifiers.add(ALPINE_XDATA_HELPER);
    state.internalIdentifiers.add(ALPINE_MAGIC_SCOPE);

    if (externs.length > 0) {
        const lines: string[] = ["declare global {"];
        for (const ext of externs) {
            if (ext.kind === "method" || ext.kind === "init") {
                lines.push(`    function ${ext.name}(): ${ext.type};`);
            } else {
                lines.push(`    let ${ext.name}: ${ext.type};`);
            }
        }
        lines.push(`}`, ``);
        state.code += lines.join("\n");
    }

    emitElements(state, roots, directiveByAttribute, ids, options.resolvedXDataByAttribute);

    state.code += `\nexport {};\n`;

    return {
        id: documentId,
        languageId: "typescript",
        code: state.code,
        mappings: state.mappings,
        internalIdentifiers: state.internalIdentifiers,
    };
}

interface BuildState {
    code: string;
    mappings: MappingEntry[];
    internalIdentifiers: Set<string>;
}

interface Snippet {
    text: string;
    id: string;
    mappings: Array<{
        sourceRange: OffsetRange;
        virtualRange: OffsetRange;
        capabilities: MappingCapabilities;
        label: string;
    }>;
    internalIdentifiers?: string[];
}

function appendSnippet(state: BuildState, snippet: Snippet): void {
    const start = state.code.length;
    state.code += snippet.text;
    for (const m of snippet.mappings) {
        state.mappings.push({
            sourceRange: m.sourceRange,
            virtualRange: {
                start: start + m.virtualRange.start,
                end: start + m.virtualRange.end,
            },
            capabilities: m.capabilities,
            label: m.label,
        });
    }
    if (snippet.internalIdentifiers) {
        for (const id of snippet.internalIdentifiers) {
            state.internalIdentifiers.add(id);
        }
    }
}

function appendRaw(state: BuildState, text: string): void {
    state.code += text;
}

function emitElements(
    state: BuildState,
    elements: ReadonlyArray<ParsedElement>,
    directiveByAttribute: ReadonlyMap<string, AlpineDirectiveNode>,
    ids: IdGen,
    resolvedXDataByAttribute: ReadonlyMap<string, ResolvedXDataSource> | undefined,
): void {
    for (const element of elements) {
        emitElement(state, element, directiveByAttribute, ids, resolvedXDataByAttribute);
    }
}

function emitElement(
    state: BuildState,
    element: ParsedElement,
    directiveByAttribute: ReadonlyMap<string, AlpineDirectiveNode>,
    ids: IdGen,
    resolvedXDataByAttribute: ReadonlyMap<string, ResolvedXDataSource> | undefined,
): void {
    const directives = element.attributes
        .map((attribute) => directiveByAttribute.get(attributeRangeKey(attribute.attributeRange)))
        .filter((directive): directive is AlpineDirectiveNode => Boolean(directive))
        .filter((directive) => STAGE4_DIRECTIVES.has(directive.canonicalName));
    const dataDirective = directives.find((directive) => directive.canonicalName === "x-data");
    if (dataDirective) {
        appendRaw(state, "{\n");
        const dataSnippet = buildSnippet(
            dataDirective,
            ids,
            resolvedXDataByAttribute?.get(attributeRangeKey(dataDirective.attributeRange)),
        );
        if (dataSnippet) {
            appendSnippet(state, dataSnippet);
        }
    }
    for (const directive of directives) {
        if (directive === dataDirective) {
            continue;
        }
        const snippet = buildSnippet(directive, ids);
        if (snippet) {
            appendSnippet(state, snippet);
        }
    }
    if (element.children.length > 0) {
        emitElements(state, element.children, directiveByAttribute, ids, resolvedXDataByAttribute);
    }
    if (dataDirective) {
        appendRaw(state, "}\n\n");
    }
}

function attributeRangeKey(range: OffsetRange): string {
    return `${range.start}:${range.end}`;
}

function buildSnippet(
    directive: AlpineDirectiveNode,
    ids: IdGen,
    resolvedXData?: ResolvedXDataSource,
): Snippet | undefined {
    switch (directive.canonicalName) {
        case "x-data":
            return buildDataSnippet(directive, ids, ids(), resolvedXData);
        case "x-on":
            return buildOnSnippet(directive, ids);
        case "x-text":
            return buildRenderSnippet(directive, "any", ids);
        case "x-show":
            return buildRenderSnippet(directive, "boolean", ids);
        case "x-bind":
            return buildBindSnippet(directive, ids);
        case "x-model":
            return buildModelSnippet(directive, ids);
        case "x-modelable":
            return buildModelableSnippet(directive, ids);
        default:
            return undefined;
    }
}

function sourceValueRange(directive: AlpineDirectiveNode): OffsetRange {
    if (directive.valueRange) {
        return directive.valueRange;
    }
    return directive.nameRange;
}

function buildDataSnippet(
    directive: AlpineDirectiveNode,
    ids: IdGen,
    scopeId: string,
    resolvedXData?: ResolvedXDataSource,
): Snippet {
    const value = directive.value ?? "{}";
    const valueRange = sourceValueRange(directive);
    const parsed = parseDataLiteral(value);
    if (!parsed.parseError && parsed.members.length > 0) {
        return buildStructuredDataSnippet(value, valueRange, valueRange.start, parsed.members, scopeId);
    }
    if (resolvedXData && resolvedXData.members.length > 0) {
        return buildStructuredDataSnippet(
            resolvedXData.expressionText,
            valueRange,
            resolvedXData.expressionRange.start,
            resolvedXData.members,
            scopeId,
        );
    }
    if (parsed.parseError || parsed.members.length === 0) {
        return buildFallbackDataSnippet(directive, value, valueRange, ids);
    }
    return buildFallbackDataSnippet(directive, value, valueRange, ids);
}

function buildStructuredDataSnippet(
    expressionText: string,
    scopeSourceRange: OffsetRange,
    memberSourceBase: number,
    members: ReadonlyArray<DataMemberDescriptor>,
    scopeId: string,
): Snippet {
    const scopePrefix = `const ${scopeId} = ${ALPINE_XDATA_HELPER}(`;
    const scopeSuffix = `);\n`;
    const magicPrelude = buildMagicPrelude();
    const magicDataBinding = buildMagicDataBinding(scopeId);
    const scopeValueStart = scopePrefix.length;
    const memberMappings: Snippet["mappings"] = [
        {
            sourceRange: scopeSourceRange,
            virtualRange: {
                start: magicPrelude.length + scopeValueStart,
                end: magicPrelude.length + scopeValueStart + expressionText.length,
            },
            capabilities: DATA_DECLARATION_CAPS,
            label: `x-data scope ${scopeId}`,
        },
        ...buildScopeMemberMappings(members, memberSourceBase, magicPrelude.length + scopeValueStart),
    ];
    const internalIds: string[] = [scopeId];
    let text = `${magicPrelude}${scopePrefix}${expressionText}${scopeSuffix}${magicDataBinding}`;
    for (const member of members) {
        const decl = emitDataMember(member, scopeId);
        if (!decl) {
            continue;
        }
        const memberStart = text.length;
        text += `${decl.text}\n`;
        if (decl.internalId) {
            internalIds.push(decl.internalId);
        }
        for (const mapping of decl.mappings) {
            memberMappings.push({
                sourceRange: {
                    start: memberSourceBase + mapping.sourceRange.start,
                    end: memberSourceBase + mapping.sourceRange.end,
                },
                virtualRange: {
                    start: memberStart + mapping.virtualRange.start,
                    end: memberStart + mapping.virtualRange.end,
                },
                capabilities: mapping.capabilities,
                label: mapping.label,
            });
        }
    }
    text += "\n";
    return {
        text,
        id: scopeId,
        mappings: memberMappings,
        internalIdentifiers: internalIds,
    };
}

function emitDataMember(
    member: DataMemberDescriptor,
    scopeId: string,
): {
    text: string;
    mappings: Snippet["mappings"];
    internalId?: string;
} | undefined {
    switch (member.kind) {
        case "property":
            return emitScopeAlias(
                member,
                `let ${member.name}: typeof ${scopeId}.${member.name} = ${scopeId}.${member.name};`,
                `x-data property ${member.name}`,
            );
        case "shorthand":
            return emitScopeAlias(
                member,
                `let ${member.name}: typeof ${scopeId}.${member.name} = ${scopeId}.${member.name};`,
                `x-data shorthand ${member.name}`,
            );
        case "method":
        case "init":
            {
                const explicitSignature = buildExplicitMethodAlias(member, scopeId);
                if (explicitSignature) {
                    return emitScopeAlias(
                        member,
                        explicitSignature,
                        `x-data ${member.kind} ${member.name}`,
                        `function ${member.name}`,
                    );
                }
            }
            return emitScopeAlias(
                member,
                `function ${member.name}(...args: Parameters<typeof ${scopeId}.${member.name}>): ReturnType<typeof ${scopeId}.${member.name}> { return ${scopeId}.${member.name}(...args); }`,
                `x-data ${member.kind} ${member.name}`,
                `function ${member.name}`,
            );
        case "getter":
            return emitScopeAlias(
                member,
                `const ${member.name}: typeof ${scopeId}.${member.name} = ${scopeId}.${member.name};`,
                `x-data getter ${member.name}`,
            );
        case "setter":
            return emitScopeAlias(
                member,
                `let ${member.name}: typeof ${scopeId}.${member.name} = ${scopeId}.${member.name};`,
                `x-data setter ${member.name}`,
            );
        default:
            return undefined;
    }
}

function buildScopeMemberMappings(
    members: ReadonlyArray<DataMemberDescriptor>,
    memberSourceBase: number,
    scopeValueStart: number,
): Snippet["mappings"] {
    const mappings: Snippet["mappings"] = [];
    for (const member of members) {
        mappings.push({
            sourceRange: {
                start: memberSourceBase + member.nameRange.start,
                end: memberSourceBase + member.nameRange.end,
            },
            virtualRange: {
                start: scopeValueStart + member.nameRange.start,
                end: scopeValueStart + member.nameRange.end,
            },
            capabilities: DATA_DECLARATION_CAPS,
            label: `x-data ${member.kind} ${member.name}`,
        });
        if (member.initializerRange) {
            mappings.push({
                sourceRange: {
                    start: memberSourceBase + member.initializerRange.start,
                    end: memberSourceBase + member.initializerRange.end,
                },
                virtualRange: {
                    start: scopeValueStart + member.initializerRange.start,
                    end: scopeValueStart + member.initializerRange.end,
                },
                capabilities: DATA_DECLARATION_CAPS,
                label: `x-data property ${member.name} value`,
            });
        }
        if (member.bodyRange) {
            mappings.push({
                sourceRange: {
                    start: memberSourceBase + member.bodyRange.start,
                    end: memberSourceBase + member.bodyRange.end,
                },
                virtualRange: {
                    start: scopeValueStart + member.bodyRange.start,
                    end: scopeValueStart + member.bodyRange.end,
                },
                capabilities: HANDLER_BODY_CAPS,
                label: `x-data ${member.kind} ${member.name} body`,
            });
        }
    }
    return mappings;
}

function emitScopeAlias(
    member: DataMemberDescriptor,
    text: string,
    label: string,
    nameNeedle = member.name,
    virtualName = member.name,
    capabilities: MappingCapabilities = DATA_ALIAS_CAPS,
): {
    text: string;
    mappings: Snippet["mappings"];
} {
    const needleStart = text.indexOf(nameNeedle);
    const nameStart = needleStart >= 0 ? text.indexOf(virtualName, needleStart) : text.indexOf(virtualName);
    return {
        text,
        mappings: [
            {
                sourceRange: member.nameRange,
                virtualRange: {
                    start: Math.max(0, nameStart),
                    end: Math.max(0, nameStart) + virtualName.length,
                },
                capabilities,
                label,
            },
        ],
    };
}

function buildExplicitMethodAlias(
    member: DataMemberDescriptor,
    scopeId: string,
): string | undefined {
    if (member.kind !== "method" && member.kind !== "init") {
        return undefined;
    }
    const parameters = member.parameters ?? [];
    const hasExplicitJsDoc = parameters.some((parameter) => Boolean(parameter.jsDocTypeText))
        || Boolean(member.jsDocReturnTypeText);
    if (!hasExplicitJsDoc) {
        return undefined;
    }
    const signature = parameters.map((parameter) => formatExplicitParameter(parameter)).join(", ");
    const forwarded = parameters.map((parameter) => parameter.isRest ? `...${parameter.name}` : parameter.name).join(", ");
    const returnType = member.jsDocReturnTypeText ?? `ReturnType<typeof ${scopeId}.${member.name}>`;
    const invocation = `${scopeId}.${member.name}(${forwarded})`;
    if (returnType === "void") {
        return `function ${member.name}(${signature}): void { ${invocation}; }`;
    }
    return `function ${member.name}(${signature}): ${returnType} { return ${invocation}; }`;
}

function formatExplicitParameter(parameter: DataMemberParameterDescriptor): string {
    const typeText = parameter.jsDocTypeText ?? "any";
    if (parameter.isRest) {
        return `...${parameter.name}: ${typeText}`;
    }
    if (parameter.hasDefault) {
        return `${parameter.name}?: ${typeText}`;
    }
    return `${parameter.name}: ${typeText}`;
}


function buildFallbackDataSnippet(
    _directive: AlpineDirectiveNode,
    value: string,
    valueRange: OffsetRange,
    _ids: IdGen,
): Snippet {
    const magicPrelude = buildMagicPrelude();
    const text = `${magicPrelude}const __alpine_data: unknown = ${value};\nconst $data: unknown = __alpine_data;\n\n`;
    return {
        text,
        id: "x-data-fallback",
        mappings: [
            {
                sourceRange: valueRange,
                virtualRange: {
                    start: magicPrelude.length + "const __alpine_data: unknown = ".length,
                    end: magicPrelude.length + "const __alpine_data: unknown = ".length + value.length,
                },
                capabilities: DATA_DECLARATION_CAPS,
                label: "x-data (literal fallback)",
            },
        ],
    };
}

function buildMagicPrelude(): string {
    return [
        `/** Alpine magic: current DOM node. */`,
        `const $el = undefined as unknown as HTMLElement;`,
        `/** Alpine magic: static refs collected from x-ref within this component. */`,
        `const $refs = undefined as unknown as Record<string, HTMLElement>;`,
        `/** Alpine magic: global Alpine stores. */`,
        `const $store = undefined as unknown as Record<string, unknown>;`,
        `/** Alpine magic: root DOM node for the current component. */`,
        `const $root = undefined as unknown as HTMLElement;`,
        `/** Alpine magic: dispatch a browser event from the current component. */`,
        `function $dispatch(name: string, detail?: unknown, options?: CustomEventInit<unknown>): boolean { void name; void detail; void options; return true; }`,
        `/** Alpine magic: watch a reactive property path. */`,
        `function $watch(path: string, callback: (value: unknown, oldValue: unknown) => void): void { void path; void callback; }`,
        `/** Alpine magic: run code after Alpine has flushed DOM updates. */`,
        `function $nextTick(callback?: () => void): Promise<void> { void callback; return Promise.resolve(); }`,
        `/** Alpine magic: generate an id unique within the current Alpine scope. */`,
        `function $id(name: string, ...keys: Array<string | number>): string { void name; void keys; return ""; }`,
        ``,
    ].join("\n");
}

function buildMagicDataBinding(scopeId: string): string {
    return [
        `/** Alpine magic: the current Alpine data scope object. */`,
        `const $data: typeof ${scopeId} = ${scopeId};`,
        ``,
    ].join("\n");
}

function isIdentifierLike(value: string): boolean {
    const trimmed = value.trim();
    return /^[A-Za-z_$][\w$]*$/.test(trimmed);
}

function buildOnSnippet(directive: AlpineDirectiveNode, ids: IdGen): Snippet {
    const eventName = directive.argument ?? "click";
    const handlerName = ids();
    const value = directive.value ?? "";
    const valueRange: OffsetRange = sourceValueRange(directive);
    const trimmedValue = value.trim();
    let body: string;
    if (isIdentifierLike(value)) {
        body = `void ${value};`;
    } else if (value.trim().length === 0) {
        body = "/* empty handler */";
    } else {
        const stmt = toStatement(value);
        body = stmt.endsWith(";") || stmt.endsWith("}") ? stmt : `${stmt};`;
    }
    const signature = `function ${handlerName}($event: Event, event: Event): void { `;
    const closing = ` }\n\n`;
    const text = signature + body + closing;
    const bodyStart = signature.length;
    const expressionOffset = trimmedValue ? Math.max(0, body.indexOf(trimmedValue)) : 0;
    const expressionLength = trimmedValue ? trimmedValue.length : body.length;
    return {
        text,
        id: handlerName,
        mappings: [
            {
                sourceRange: valueRange,
                virtualRange: {
                    start: bodyStart + expressionOffset,
                    end: bodyStart + expressionOffset + expressionLength,
                },
                capabilities: HANDLER_BODY_CAPS,
                label: `x-on handler ${eventName}`,
            },
        ],
        internalIdentifiers: [handlerName],
    };
}

function toStatement(expression: string): string {
    const trimmed = expression.trim();
    if (trimmed.endsWith(";")) {
        return trimmed;
    }
    if (trimmed.startsWith("return") || trimmed.startsWith("if") || trimmed.startsWith("for") || trimmed.startsWith("while")) {
        return trimmed;
    }
    return `${trimmed};`;
}

function buildRenderSnippet(
    directive: AlpineDirectiveNode,
    returnKind: string,
    ids: IdGen,
): Snippet {
    const name = ids();
    const value = directive.value ?? "";
    const valueRange: OffsetRange = sourceValueRange(directive);
    const signature = `function ${name}(): ${returnKind} { return `;
    const body = `${value};`;
    const closing = ` }\n\n`;
    const text = signature + body + closing;
    const bodyStart = signature.length;
    return {
        text,
        id: name,
        mappings: [
            {
                sourceRange: valueRange,
                virtualRange: {
                    start: bodyStart,
                    end: bodyStart + value.length,
                },
                capabilities: RENDER_EXPRESSION_CAPS,
                label: `${directive.canonicalName} expression`,
            },
        ],
        internalIdentifiers: [name],
    };
}

function buildBindSnippet(directive: AlpineDirectiveNode, ids: IdGen): Snippet {
    const target = directive.argument ?? "value";
    const name = ids();
    const value = directive.value ?? "";
    const valueRange: OffsetRange = sourceValueRange(directive);
    const signature = `function ${name}(value: unknown): ${mapBindTarget(target)} { return `;
    const body = `${value};`;
    const closing = ` }\n\n`;
    const text = signature + body + closing;
    const bodyStart = signature.length;
    return {
        text,
        id: name,
        mappings: [
            {
                sourceRange: valueRange,
                virtualRange: {
                    start: bodyStart,
                    end: bodyStart + value.length,
                },
                capabilities: RENDER_EXPRESSION_CAPS,
                label: `x-bind ${target}`,
            },
        ],
        internalIdentifiers: [name],
    };
}

function mapBindTarget(target: string): string {
    switch (target) {
        case "class":
        case "style":
            return "string";
        default:
            return target === "disabled" || target === "hidden" || target === "readonly" || target === "checked"
                ? "boolean"
                : target === "value" || target === "href"
                ? "string"
                : "unknown";
    }
}

function buildModelSnippet(directive: AlpineDirectiveNode, ids: IdGen): Snippet {
    const handlerName = ids();
    const value = directive.value ?? "";
    const valueRange: OffsetRange = sourceValueRange(directive);
    const signature = `function ${handlerName}(newValue: unknown): void { /* x-model */ void newValue; void `;
    const body = `${value};`;
    const closing = ` }`;
    const text = signature + body + closing;
    const bodyStart = signature.length;
    return {
        text,
        id: handlerName,
        mappings: [
            {
                sourceRange: valueRange,
                virtualRange: {
                    start: bodyStart,
                    end: bodyStart + value.length,
                },
                capabilities: RENDER_EXPRESSION_CAPS,
                label: "x-model expression",
            },
        ],
        internalIdentifiers: [handlerName],
    };
}

function buildModelableSnippet(directive: AlpineDirectiveNode, ids: IdGen): Snippet {
    const getterName = ids();
    const value = directive.value ?? "";
    const valueRange: OffsetRange = sourceValueRange(directive);
    const signature = `function ${getterName}(): unknown { return `;
    const body = `${value};`;
    const closing = ` }`;
    const text = signature + body + closing;
    const bodyStart = signature.length;
    return {
        text,
        id: getterName,
        mappings: [
            {
                sourceRange: valueRange,
                virtualRange: {
                    start: bodyStart,
                    end: bodyStart + value.length,
                },
                capabilities: RENDER_EXPRESSION_CAPS,
                label: "x-modelable expression",
            },
        ],
        internalIdentifiers: [getterName],
    };
}

export function isStage4SupportedDirective(canonicalName: string): boolean {
    return STAGE4_DIRECTIVES.has(canonicalName);
}

export interface HandlerReferenceInfo {
    identifier: string;
    isReference: boolean;
}

export function isHandlerReference(value: string | undefined): HandlerReferenceInfo {
    if (!value) {
        return { identifier: "", isReference: false };
    }
    const trimmed = value.trim();
    const match = trimmed.match(/^([A-Za-z_$][\w$]*)$/);
    if (match && match[1]) {
        return { identifier: match[1], isReference: true };
    }
    return { identifier: "", isReference: false };
}

export const _internal = {};
